language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "9"
install:
  - yarn install
scripts:
  yarn clean
branches:
  only:
    - master
before_deploy:
  yarn generate
#   yarn deploy
deploy:
  provider: pages
  email: $NPM_EMAIL
  github-token: $GITHUB_TOKEN
  keep-history: true
  skip-cleanup: true
  on:
    branch: master